//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System_Database.DB_Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebAPI_DatabaseEntities : DbContext
    {
        public WebAPI_DatabaseEntities()
            : base("name=WebAPI_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_bookings> tbl_bookings { get; set; }
        public virtual DbSet<tbl_hotels> tbl_hotels { get; set; }
        public virtual DbSet<tbl_rooms> tbl_rooms { get; set; }
    }
}
