//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System_Database.DB_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bookings
    {
        public int Booking_Id { get; set; }
        public int Room_Id { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string Status { get; set; }
    
        public virtual tbl_rooms tbl_rooms { get; set; }
    }
}
