//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System_Database.DB_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_rooms()
        {
            this.tbl_bookings = new HashSet<tbl_bookings>();
        }
    
        public int Room_Id { get; set; }
        public int Hotel_Id { get; set; }
        public string RoomName { get; set; }
        public string Category { get; set; }
        public int Price { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_bookings> tbl_bookings { get; set; }
        public virtual tbl_hotels tbl_hotels { get; set; }
    }
}
