//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_Products
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [MinLength(4, ErrorMessage = "Please enter minimum 4 characters. ")]
     //   [Display(Name = "Enter your Username")]
        public string Name { get; set; }


        [Required(ErrorMessage = "This field is required")]
    //    [Display(Name = "Enter Category of Product")]
        public int Category { get; set; }


        [Required(ErrorMessage = "This field is required")]
    //    [Display(Name = "Enter Price of Product")]
        public int Price { get; set; }



        [Required(ErrorMessage = "This field is required")]
     //   [Display(Name = "Enter Quantity of Product")]
        public int Quantity { get; set; }


        [Required(ErrorMessage = "This field is required")]
    //    [Display(Name = "Enter Short Desciption of  Product")]
        [MinLength(7, ErrorMessage = "Please enter minimum 7 characters. ")]
        public string ShortDescription { get; set; }


        [Required(ErrorMessage = "This field is required")]
    //    [Display(Name = "Enter Short Desciption of  Product")]
        [MinLength(10, ErrorMessage = "Please enter minimum 10 characters. ")]
        public string LongDescription { get; set; }


        [Required(ErrorMessage = "This field is required")]
        public string SmallImage { get; set; }


        [Required(ErrorMessage = "This field is required")]
        public string LargeImage { get; set; }
    
        public virtual tbl_Categories tbl_Categories { get; set; }
    }
}
